# Generated by Django 6.0.4 on 2026-04-21 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='uploads/Departamentos')),
                ('ubicacion', models.CharField(max_length=30)),
                ('cantHabitaciones', models.IntegerField()),
                ('mobiliario', models.CharField(max_length=300)),
                ('servicios', models.CharField(max_length=200)),
                ('estadoInicial', models.CharField(max_length=300)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telefonoAlt', models.IntegerField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departamentos.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='uploads/Contratos')),
                ('monto', models.PositiveBigIntegerField()),
                ('inicio', models.DateField()),
                ('pago', models.DateField()),
                ('mantenimiento', models.CharField(max_length=500)),
                ('cancelacion', models.CharField(null=True)),
                ('pautas', models.CharField(max_length=300, null=True)),
                ('aumentos', models.IntegerField()),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departamentos.inquilino')),
            ],
        ),
    ]
