# Generated by Django 6.0.4 on 2026-05-05 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='uploads/Departamentos')),
                ('ubicacion', models.TextField(max_length=30)),
                ('cantHabitaciones', models.IntegerField()),
                ('mobiliario', models.TextField(blank=True, max_length=300, null=True)),
                ('servicios', models.TextField(blank=True, max_length=200, null=True)),
                ('estadoInicial', models.TextField(blank=True, max_length=300, null=True)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fotosDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='uploads/')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departamentos.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('telefonoAlt', models.IntegerField(blank=True, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departamentos.departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='uploads/Contratos')),
                ('monto', models.PositiveBigIntegerField()),
                ('inicio', models.DateField()),
                ('pago', models.DateField(blank=True, null=True)),
                ('mantenimiento', models.TextField(blank=True, max_length=500, null=True)),
                ('cancelacion', models.TextField(blank=True, null=True)),
                ('pautas', models.TextField(blank=True, max_length=300, null=True)),
                ('aumentos', models.IntegerField()),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departamentos.inquilino')),
            ],
        ),
    ]
