# Generated by Django 6.0.4 on 2026-04-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/Contratos'),
        ),
    ]
