# Generated by Django 6.0.4 on 2026-04-26 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departamentos', '0002_alter_contrato_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='fotosDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='uploads/')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departamentos.departamento')),
            ],
        ),
    ]
